FROM python:3.8-slim-buster

LABEL maintainer="Joshua Noakes" \
    description="Speedtest to InfluxDB data bridge | Origin: https://github.com/aidengilmartin/speedtest-to-influxdb"

# Install dependencies
ENV DEBIAN_FRONTEND=noninteractive

COPY requirements.txt /

RUN apt-get update && \
    apt-get dist-upgrade -y

# Install speedtest CLI
RUN mkdir /opt/speedtest
RUN wget https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-x86_64-linux.tgz -O /opt/speedtest/ookla-speedtest-1.0.0-x86_64-linux.tgz
RUN tar zxvf /opt/speedtest/ookla-speedtest-1.0.0-x86_64-linux.tgz -C /opt/speedtest/
RUN rm -rf /opt/speedtest/ookla-speedtest-1.0.0-x86_64-linux.tgz
RUN chmod +x /opt/speedtest/speedtest
RUN chmod 777 /opt/speedtest/speedtest
RUN ln -s /opt/speedtest/speedtest /bin/speedtest

RUN apt-get -q -y autoremove && \
    apt-get -q -y clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install -r /requirements.txt

# Final setup & execution
COPY speedtest2influx.py /app/speedtest2influx.py
WORKDIR /app
CMD ["python3", "-u", "speedtest2influx.py"]
